In [4]:
import pandas as pd

df = pd.read_csv("../datasets/phishing_urls/Phishing_url.csv")

print(df.shape)

(235795, 55)

In [5]:
df.head()

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,...,0,0,1,34,20,28,119,0,124,1
1,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,...,0,0,1,50,9,8,39,0,217,1
2,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,...,0,0,1,10,2,7,42,2,5,1
3,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,...,1,1,1,3,27,15,22,1,31,1
4,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,...,1,0,1,244,15,34,72,1,85,1

In [6]:
df.columns.tolist()

['URL',
 'URLLength',
 'Domain',
 'DomainLength',
 'IsDomainIP',
 'TLD',
 'URLSimilarityIndex',
 'CharContinuationRate',
 'TLDLegitimateProb',
 'URLCharProb',
 'TLDLength',
 'NoOfSubDomain',
 'HasObfuscation',
 'NoOfObfuscatedChar',
 'ObfuscationRatio',
 'NoOfLettersInURL',
 'LetterRatioInURL',
 'NoOfDegitsInURL',
 'DegitRatioInURL',
 'NoOfEqualsInURL',
 'NoOfQMarkInURL',
 'NoOfAmpersandInURL',
 'NoOfOtherSpecialCharsInURL',
 'SpacialCharRatioInURL',
 'IsHTTPS',
 'LineOfCode',
 'LargestLineLength',
 'HasTitle',
 'Title',
 'DomainTitleMatchScore',
 'URLTitleMatchScore',
 'HasFavicon',
 'Robots',
 'IsResponsive',
 'NoOfURLRedirect',
 'NoOfSelfRedirect',
 'HasDescription',
 'NoOfPopup',
 'NoOfiFrame',
 'HasExternalFormSubmit',
 'HasSocialNet',
 'HasSubmitButton',
 'HasHiddenFields',
 'HasPasswordField',
 'Bank',
 'Pay',
 'Crypto',
 'HasCopyrightInfo',
 'NoOfImage',
 'NoOfCSS',
 'NoOfJS',
 'NoOfSelfRef',
 'NoOfEmptyRef',
 'NoOfExternalRef',
 'label']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 55 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   URL                         235795 non-null  str
 1   URLLength                   235795 non-null  int64
 2   Domain                      235795 non-null  str
 3   DomainLength                235795 non-null  int64
 4   IsDomainIP                  235795 non-null  int64
 5   TLD                         235795 non-null  str
 6   URLSimilarityIndex          235795 non-null  float64
 7   CharContinuationRate        235795 non-null  float64
 8   TLDLegitimateProb           235795 non-null  float64
 9   URLCharProb                 235795 non-null  float64
 10  TLDLength                   235795 non-null  int64
 11  NoOfSubDomain               235795 non-null  int64
 12  HasObfuscation              235795 non-null  int64
 13  NoOfObfuscatedChar          235795 non-null  int64
 14  ObfuscationRatio            235795 non-null  float64
 15  NoOfLettersInURL            235795 non-null  int64
 16  LetterRatioInURL            235795 non-null  float64
 17  NoOfDegitsInURL             235795 non-null  int64
 18  DegitRatioInURL             235795 non-null  float64
 19  NoOfEqualsInURL             235795 non-null  int64
 20  NoOfQMarkInURL              235795 non-null  int64
 21  NoOfAmpersandInURL          235795 non-null  int64
 22  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 23  SpacialCharRatioInURL       235795 non-null  float64
 24  IsHTTPS                     235795 non-null  int64
 25  LineOfCode                  235795 non-null  int64
 26  LargestLineLength           235795 non-null  int64
 27  HasTitle                    235795 non-null  int64
 28  Title                       235795 non-null  str
 29  DomainTitleMatchScore       235795 non-null  float64
 30  URLTitleMatchScore          235795 non-null  float64
 31  HasFavicon                  235795 non-null  int64
 32  Robots                      235795 non-null  int64
 33  IsResponsive                235795 non-null  int64
 34  NoOfURLRedirect             235795 non-null  int64
 35  NoOfSelfRedirect            235795 non-null  int64
 36  HasDescription              235795 non-null  int64
 37  NoOfPopup                   235795 non-null  int64
 38  NoOfiFrame                  235795 non-null  int64
 39  HasExternalFormSubmit       235795 non-null  int64
 40  HasSocialNet                235795 non-null  int64
 41  HasSubmitButton             235795 non-null  int64
 42  HasHiddenFields             235795 non-null  int64
 43  HasPasswordField            235795 non-null  int64
 44  Bank                        235795 non-null  int64
 45  Pay                         235795 non-null  int64
 46  Crypto                      235795 non-null  int64
 47  HasCopyrightInfo            235795 non-null  int64
 48  NoOfImage                   235795 non-null  int64
 49  NoOfCSS                     235795 non-null  int64
 50  NoOfJS                      235795 non-null  int64
 51  NoOfSelfRef                 235795 non-null  int64
 52  NoOfEmptyRef                235795 non-null  int64
 53  NoOfExternalRef             235795 non-null  int64
 54  label                       235795 non-null  int64
dtypes: float64(10), int64(41), str(4)
memory usage: 115.9 MB

In [8]:
df["label"].value_counts()

label
1    134850
0    100945
Name: count, dtype: int64

In [9]:
# Remove raw text columns
#drop_cols = ['URL', 'Domain', 'TLD', 'Title']
#df_model = df.drop(columns=drop_cols)
#print("New shape:", df_model.shape)
#print(df_model.head())

# Filter dataset to ONLY the 18 production-ready lexical URL features
LEGAL_FEATURES = [
    'URLLength', 'DomainLength', 'IsDomainIP', 'TLDLength', 'NoOfSubDomain',
    'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio', 
    'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL', 
    'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 
    'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL', 
    'SpacialCharRatioInURL', 'IsHTTPS'
]

X = df[LEGAL_FEATURES]
y = df['label']

print("X shape (18 Features):", X.shape)
print("y shape:", y.shape)

X shape (18 Features): (235795, 18)
y shape: (235795,)

In [7]:
# Separate features and target
X = df_model.drop(columns=['label'])
y = df_model['label']

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\nLabel distribution:")
print(y.value_counts())

X shape: (235795, 50)
y shape: (235795,)

Label distribution:
label
1    134850
0    100945
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

print("\nTraining labels:")
print(y_train.value_counts())

print("\nTesting labels:")
print(y_test.value_counts())

Training data: (188636, 50)
Testing data: (47159, 50)

Training labels:
label
1    107880
0     80756
Name: count, dtype: int64

Testing labels:
label
1    26970
0    20189
Name: count, dtype: int64

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled training shape:", X_train_scaled.shape)
print("Scaled testing shape:", X_test_scaled.shape)

Scaled training shape: (188636, 50)
Scaled testing shape: (47159, 50)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Create model
lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

# Train
lr_model.fit(X_train_scaled, y_train)

# Predict
y_pred_lr = lr_model.predict(X_test_scaled)

# Accuracy
lr_accuracy = accuracy_score(y_test, y_pred_lr)

print("Logistic Regression Accuracy:", lr_accuracy)

# Detailed evaluation
print("\nClassification Report:")
print(classification_report(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.9998727708390763

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     20189
           1       1.00      1.00      1.00     26970

    accuracy                           1.00     47159
   macro avg       1.00      1.00      1.00     47159
weighted avg       1.00      1.00      1.00     47159

In [11]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

# Create model
svm_model = LinearSVC(
    random_state=42,
    max_iter=2000
)

# Train
svm_model.fit(X_train_scaled, y_train)

# Predict
y_pred_svm = svm_model.predict(X_test_scaled)

# Accuracy
svm_accuracy = accuracy_score(y_test, y_pred_svm)

print("Linear SVM Accuracy:", svm_accuracy)

# Detailed evaluation
print("\nClassification Report:")
print(classification_report(y_test, y_pred_svm))

Linear SVM Accuracy: 0.9999151805593842

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     20189
           1       1.00      1.00      1.00     26970

    accuracy                           1.00     47159
   macro avg       1.00      1.00      1.00     47159
weighted avg       1.00      1.00      1.00     47159

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Create model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

# Train
rf_model.fit(X_train, y_train)

# Predict
y_pred_rf = rf_model.predict(X_test)

# Accuracy
rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", rf_accuracy)

# Detailed evaluation
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     20189
           1       1.00      1.00      1.00     26970

    accuracy                           1.00     47159
   macro avg       1.00      1.00      1.00     47159
weighted avg       1.00      1.00      1.00     47159

In [13]:
!pip install xgboost

Requirement already satisfied: xgboost in C:\Users\Aman\anaconda3\Lib\site-packages (3.4.1)
Requirement already satisfied: numpy in C:\Users\Aman\anaconda3\Lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in C:\Users\Aman\anaconda3\Lib\site-packages (from xgboost) (1.18.0)

In [14]:
import xgboost

print("XGBoost version:", xgboost.__version__)

XGBoost version: 3.4.1

In [15]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

# Create model
xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    n_jobs=-1,
    eval_metric='logloss'
)

# Train
xgb_model.fit(X_train, y_train)

# Predict
y_pred_xgb = xgb_model.predict(X_test)

# Accuracy
xgb_accuracy = accuracy_score(y_test, y_pred_xgb)

print("XGBoost Accuracy:", xgb_accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

XGBoost Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     20189
           1       1.00      1.00      1.00     26970

    accuracy                           1.00     47159
   macro avg       1.00      1.00      1.00     47159
weighted avg       1.00      1.00      1.00     47159

In [16]:
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score

results = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Linear SVM',
        'Random Forest',
        'XGBoost'
    ],
    'Accuracy': [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_svm),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_xgb)
    ],
    'Precision': [
        precision_score(y_test, y_pred_lr),
        precision_score(y_test, y_pred_svm),
        precision_score(y_test, y_pred_rf),
        precision_score(y_test, y_pred_xgb)
    ],
    'Recall': [
        recall_score(y_test, y_pred_lr),
        recall_score(y_test, y_pred_svm),
        recall_score(y_test, y_pred_rf),
        recall_score(y_test, y_pred_xgb)
    ],
    'F1 Score': [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_svm),
        f1_score(y_test, y_pred_rf),
        f1_score(y_test, y_pred_xgb)
    ]
})

results = results.sort_values('F1 Score', ascending=False)

results

                 Model  Accuracy  Precision  Recall  F1 Score
3              XGBoost  1.000000   1.000000     1.0  1.000000
2        Random Forest  1.000000   1.000000     1.0  1.000000
1           Linear SVM  0.999915   0.999852     1.0  0.999926
0  Logistic Regression  0.999873   0.999778     1.0  0.999889

In [17]:
print("Duplicate rows:", df_model.duplicated().sum())
print("Duplicate URLs:", df['URL'].duplicated().sum())

train_urls = set(df.loc[X_train.index, 'URL'])
test_urls = set(df.loc[X_test.index, 'URL'])

overlap = train_urls.intersection(test_urls)

print("URLs in both train and test:", len(overlap))

Duplicate rows: 808
Duplicate URLs: 425
URLs in both train and test: 143

In [18]:
df[df['URL'].duplicated(keep=False)].sort_values('URL')

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
57609,http://2f3a.reicrut-chat.workers.dev/,36,2f3a.reicrut-chat.workers.dev,29,0,dev,27.903290,0.360000,0.000961,0.051950,...,1,0,0,0,0,0,0,0,0,0
219489,http://2f3a.reicrut-chat.workers.dev/,37,2f3a.reicrut-chat.workers.dev,29,0,dev,27.903290,0.360000,0.000961,0.051950,...,1,0,0,0,0,0,0,0,0,0
27166,http://34.149.138.117/,22,34.149.138.117,14,1,117,38.231293,0.400000,0.000000,0.001404,...,0,1,0,4,1,4,48,0,9,0
227564,http://34.149.138.117/,21,34.149.138.117,14,1,117,38.231293,0.400000,0.000000,0.001404,...,0,1,0,4,1,5,48,0,9,0
147448,http://595221.selcdn.ru/qwerty-ohdhdjejnnad-na...,62,595221.selcdn.ru,16,0,ru,27.442490,1.000000,0.018013,0.039487,...,0,0,1,2,2,7,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218592,https://yahoo-109157.weeblysite.com/,36,yahoo-109157.weeblysite.com,27,0,com,54.301391,0.739130,0.522907,0.045900,...,0,0,0,0,0,0,0,0,1,0
14008,https://yasssouadjanclecles.web.app/,36,yasssouadjanclecles.web.app,27,0,app,34.391534,0.869565,0.001502,0.054936,...,0,0,0,0,0,0,0,0,3,0
137897,https://yasssouadjanclecles.web.app/,35,yasssouadjanclecles.web.app,27,0,app,34.391534,0.869565,0.001502,0.054936,...,0,0,0,0,0,0,0,0,3,0
207435,https://yellow-river-189b.lhziiz35.workers.dev/,46,yellow-river-189b.lhziiz35.workers.dev,38,0,dev,29.732225,0.323529,0.000961,0.040934,...,0,0,0,0,0,4,0,0,0,0
235738,https://yellow-river-189b.lhziiz35.workers.dev/,47,yellow-river-189b.lhziiz35.workers.dev,38,0,dev,29.732225,0.323529,0.000961,0.040934,...,0,0,0,0,0,4,0,0,0,0

In [19]:
url_label_counts = df.groupby('URL')['label'].nunique()

print("URLs having multiple labels:",
      (url_label_counts > 1).sum())

URLs having multiple labels: 0

In [21]:
from sklearn.model_selection import GroupShuffleSplit

# Features and target
X = df_model.drop(columns=['label'])
y = df_model['label']

# URL from original dataframe, used ONLY for grouping
groups = df['URL']

# Split by URL so the same URL cannot enter both train and test
gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    gss.split(X, y, groups=groups)
)

X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]

y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

print("\nTraining labels:")
print(y_train.value_counts())

print("\nTesting labels:")
print(y_test.value_counts())

Training data: (188630, 50)
Testing data: (47165, 50)

Training labels:
label
1    107611
0     81019
Name: count, dtype: int64

Testing labels:
label
1    27239
0    19926
Name: count, dtype: int64

In [22]:
train_urls = set(df['URL'].iloc[train_idx])
test_urls = set(df['URL'].iloc[test_idx])

overlap = train_urls.intersection(test_urls)

print("URLs in both train and test:", len(overlap))

URLs in both train and test: 0

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled training shape:", X_train_scaled.shape)
print("Scaled testing shape:", X_test_scaled.shape)

Scaled training shape: (188630, 50)
Scaled testing shape: (47165, 50)

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_model.fit(X_train_scaled, y_train)

lr_pred = lr_model.predict(X_test_scaled)

lr_accuracy = accuracy_score(y_test, lr_pred)
lr_precision = precision_score(y_test, lr_pred)
lr_recall = recall_score(y_test, lr_pred)
lr_f1 = f1_score(y_test, lr_pred)

print("Logistic Regression Accuracy:", lr_accuracy)

print("\nClassification Report:")
print(classification_report(y_test, lr_pred))

Logistic Regression Accuracy: 0.9999363935121383

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19926
           1       1.00      1.00      1.00     27239

    accuracy                           1.00     47165
   macro avg       1.00      1.00      1.00     47165
weighted avg       1.00      1.00      1.00     47165

In [25]:
import pandas as pd

# Correlation of every numeric feature with the target
correlations = df_model.corr(numeric_only=True)['label'].drop('label')

print(correlations.abs().sort_values(ascending=False).head(15))

URLSimilarityIndex       0.860358
HasSocialNet             0.784255
HasCopyrightInfo         0.743358
HasDescription           0.690232
IsHTTPS                  0.609132
DomainTitleMatchScore    0.584905
HasSubmitButton          0.578561
IsResponsive             0.548608
URLTitleMatchScore       0.539419
SpacialCharRatioInURL    0.533537
HasHiddenFields          0.507731
HasFavicon               0.493711
URLCharProb              0.469749
CharContinuationRate     0.467735
HasTitle                 0.459725
Name: label, dtype: float64

In [26]:
print(df_model.groupby('label').mean(numeric_only=True).T.sort_values(
    by=0, ascending=False
).head(15))

label                                  0            1
LargestLineLength           20021.448244  7375.919555
LineOfCode                     65.730467  1947.491680
URLSimilarityIndex             49.616973   100.000000
URLLength                      45.720293    26.228610
NoOfLettersInURL               28.106583    12.933059
DomainLength                   24.465144    19.228610
URLTitleMatchScore             21.198164    75.270904
DomainTitleMatchScore          16.548205    75.270904
NoOfDegitsInURL                 4.326217     0.050597
NoOfOtherSpecialCharsInURL      3.803467     1.244835
TLDLength                       2.819327     2.723382
NoOfSubDomain                   1.168894     1.161661
NoOfExternalRef                 1.128119    85.294601
NoOfJS                          0.890336    17.732532
NoOfImage                       0.866492    44.946600

In [27]:
print(pd.crosstab(
    pd.cut(df_model['URLSimilarityIndex'], bins=10),
    df_model['label'],
    normalize='index'
))

label                      0         1
URLSimilarityIndex
(0.0557, 10.14]     1.000000  0.000000
(10.14, 20.124]     1.000000  0.000000
(20.124, 30.109]    1.000000  0.000000
(30.109, 40.093]    1.000000  0.000000
(40.093, 50.078]    1.000000  0.000000
(50.078, 60.062]    1.000000  0.000000
(60.062, 70.047]    1.000000  0.000000
(70.047, 80.031]    1.000000  0.000000
(80.031, 90.016]    1.000000  0.000000
(90.016, 100.0]     0.013656  0.986344

In [28]:
print(df_model.groupby('label')['URLSimilarityIndex'].agg([
    'min', 'max', 'mean', 'median', 'std'
]))

              min    max        mean      median        std
label
0        0.155574  100.0   49.616973   51.419332  22.572082
1      100.000000  100.0  100.000000  100.000000   0.000000