In [1]:
# ============================================================
# TRUSTGUARD — PHASE 5B SMOKE TEST
# ============================================================

import os
import sys
import json
import pandas as pd

BASE_DIR = r"C:\Users\Aman\Desktop\TrustGuard\product_scam_ml"

ML_SERVICE_DIR = os.path.join(
    BASE_DIR,
    "ml-service"
)

if ML_SERVICE_DIR not in sys.path:
    sys.path.insert(0, ML_SERVICE_DIR)

from phase5b_risk_engine import predict_product_risk

print("✓ Phase 5B risk engine imported successfully.")

✓ Phase 5B risk engine imported successfully.

In [2]:
# ============================================================
# TEST 1 — NORMAL PRODUCT
# ============================================================

normal_product = {
    "title": "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    
    "description": (
        "Industry-leading noise cancellation with exceptional "
        "sound quality, long battery life, and comfortable "
        "design for everyday listening."
    ),
    
    "features": [
        "Industry-leading noise cancellation",
        "Up to 30 hours of battery life",
        "Multipoint Bluetooth connection",
        "Comfortable lightweight design"
    ],
    
    "categories": [
        "Electronics",
        "Headphones",
        "Over-Ear Headphones"
    ],
    
    "images": {
        "large": [
            "https://example.com/image1.jpg",
            "https://example.com/image2.jpg"
        ]
    },
    
    "videos": {
        "url": [
            "https://example.com/video1.mp4"
        ]
    },
    
    "store": "Sony",
    
    "price": 349.99,
    
    "average_rating": 4.5,
    
    "rating_number": 12500
}

normal_result = predict_product_risk(
    normal_product
)

print(
    json.dumps(
        normal_result,
        indent=4
    )
)

{
    "risk_score": 49.67,
    "risk_level": "MEDIUM",
    "is_anomaly": true,
    "anomaly_score": 82.78,
    "indicator_score": 0.0,
    "isolation_forest": {
        "prediction": -1,
        "decision_score": -0.004269,
        "score_samples": -0.534869
    },
    "risk_weights": {
        "isolation_forest": 0.6,
        "risk_indicators": 0.4
    },
    "explanations": [
        {
            "type": "model",
            "indicator": "isolation_forest",
            "weight": 0.6,
            "explanation": "Product metadata is highly anomalous relative to the reference metadata distribution."
        }
    ]
}

In [3]:
# ============================================================
# TEST 2 — SUSPICIOUS PRODUCT
# ============================================================

suspicious_product = {
    "title": "BEST AMAZING PRODUCT!!!",
    
    "description": (
        "Amazing product."
    ),
    
    "features": [
        "Best quality"
    ],
    
    "categories": [
        "Electronics",
        "Accessories"
    ],
    
    "images": {},
    
    "videos": {},
    
    "store": None,
    
    "price": 9999,
    
    "average_rating": 4.9,
    
    "rating_number": 4
}

suspicious_result = predict_product_risk(
    suspicious_product
)

print(
    json.dumps(
        suspicious_result,
        indent=4
    )
)

{
    "risk_score": 96.36,
    "risk_level": "CRITICAL",
    "is_anomaly": true,
    "anomaly_score": 100.0,
    "indicator_score": 90.91,
    "isolation_forest": {
        "prediction": -1,
        "decision_score": -0.09563,
        "score_samples": -0.62623
    },
    "risk_weights": {
        "isolation_forest": 0.6,
        "risk_indicators": 0.4
    },
    "explanations": [
        {
            "type": "risk_indicator",
            "indicator": "high_rating_low_reviews",
            "weight": 1.5,
            "explanation": "Product has a high rating but very few reviews."
        },
        {
            "type": "risk_indicator",
            "indicator": "extreme_rating",
            "weight": 1.0,
            "explanation": "Product has an unusually extreme rating."
        },
        {
            "type": "risk_indicator",
            "indicator": "very_low_review_count",
            "weight": 1.0,
            "explanation": "Product has very few reviews."
        },
        {
            "type": "risk_indicator",
            "indicator": "missing_seller",
            "weight": 1.0,
            "explanation": "Seller information is missing."
        },
        {
            "type": "model",
            "indicator": "isolation_forest",
            "weight": 0.6,
            "explanation": "Product metadata is highly anomalous relative to the reference metadata distribution."
        }
    ]
}

In [4]:
# ============================================================
# TEST 3 — HIGHLY SUSPICIOUS PRODUCT
# ============================================================

critical_product = {
    "title": "SALE!!!",
    
    "description": "Buy now.",
    
    "features": [],
    
    "categories": [
        "Electronics"
    ],
    
    "images": {},
    
    "videos": {},
    
    "store": "",
    
    "price": None,
    
    "average_rating": 5.0,
    
    "rating_number": 1
}

critical_result = predict_product_risk(
    critical_product
)

print(
    json.dumps(
        critical_result,
        indent=4
    )
)

{
    "risk_score": 100.0,
    "risk_level": "CRITICAL",
    "is_anomaly": true,
    "anomaly_score": 100.0,
    "indicator_score": 100.0,
    "isolation_forest": {
        "prediction": -1,
        "decision_score": -0.093476,
        "score_samples": -0.624075
    },
    "risk_weights": {
        "isolation_forest": 0.6,
        "risk_indicators": 0.4
    },
    "explanations": [
        {
            "type": "risk_indicator",
            "indicator": "high_rating_low_reviews",
            "weight": 1.5,
            "explanation": "Product has a high rating but very few reviews."
        },
        {
            "type": "risk_indicator",
            "indicator": "extreme_rating",
            "weight": 1.0,
            "explanation": "Product has an unusually extreme rating."
        },
        {
            "type": "risk_indicator",
            "indicator": "very_low_review_count",
            "weight": 1.0,
            "explanation": "Product has very few reviews."
        },
        {
            "type": "risk_indicator",
            "indicator": "missing_seller",
            "weight": 1.0,
            "explanation": "Seller information is missing."
        },
        {
            "type": "model",
            "indicator": "isolation_forest",
            "weight": 0.6,
            "explanation": "Product metadata is highly anomalous relative to the reference metadata distribution."
        }
    ]
}

In [5]:
# ============================================================
# PHASE 5B — RESULT COMPARISON
# ============================================================

results = pd.DataFrame([
    {
        "product": "Normal",
        "risk_score": normal_result["risk_score"],
        "risk_level": normal_result["risk_level"],
        "anomaly_score": normal_result["anomaly_score"],
        "indicator_score": normal_result["indicator_score"],
        "is_anomaly": normal_result["is_anomaly"]
    },
    {
        "product": "Suspicious",
        "risk_score": suspicious_result["risk_score"],
        "risk_level": suspicious_result["risk_level"],
        "anomaly_score": suspicious_result["anomaly_score"],
        "indicator_score": suspicious_result["indicator_score"],
        "is_anomaly": suspicious_result["is_anomaly"]
    },
    {
        "product": "Critical",
        "risk_score": critical_result["risk_score"],
        "risk_level": critical_result["risk_level"],
        "anomaly_score": critical_result["anomaly_score"],
        "indicator_score": critical_result["indicator_score"],
        "is_anomaly": critical_result["is_anomaly"]
    }
])

display(results)

,product,risk_score,risk_level,anomaly_score,indicator_score,is_anomaly
0,Normal,49.67,MEDIUM,82.78,0.00,True
1,Suspicious,96.36,CRITICAL,100.00,90.91,True
2,Critical,100.00,CRITICAL,100.00,100.00,True

In [6]:
# ============================================================
# PHASE 5B — PRODUCTION RISK ENGINE EDGE-CASE TEST
# ============================================================

test_products = {

    "normal_complete": {
        "title": "Wireless Bluetooth Headphones with Noise Cancellation",
        "description": "Comfortable wireless headphones with long battery life and high quality sound.",
        "features": [
            "Bluetooth connectivity",
            "Noise cancellation",
            "Long battery life"
        ],
        "categories": [
            "Electronics",
            "Headphones"
        ],
        "images": {
            "large": [
                "https://example.com/image1.jpg",
                "https://example.com/image2.jpg"
            ]
        },
        "videos": {
            "url": [
                "https://example.com/video.mp4"
            ]
        },
        "store": "Example Electronics",
        "price": "49.99",
        "average_rating": 4.2,
        "rating_number": 150
    },

    "missing_metadata": {
        "title": "Product",
        "description": "",
        "features": [],
        "categories": [],
        "images": {},
        "videos": {},
        "store": "",
        "price": None,
        "average_rating": None,
        "rating_number": None
    },

    "suspicious": {
        "title": "Amazing Product",
        "description": "Best product ever.",
        "features": [],
        "categories": ["Electronics"],
        "images": {},
        "videos": {},
        "store": "",
        "price": "9.99",
        "average_rating": 5.0,
        "rating_number": 2
    }
}


results = []

for name, product in test_products.items():

    result = predict_product_risk(product)

    results.append({
        "product": name,
        "risk_score": result["risk_score"],
        "risk_level": result["risk_level"],
        "anomaly_score": result["anomaly_score"],
        "indicator_score": result["indicator_score"],
        "is_anomaly": result["is_anomaly"]
    })

results_df = pd.DataFrame(results)

display(results_df)

,product,risk_score,risk_level,anomaly_score,indicator_score,is_anomaly
0,normal_complete,34.88,MEDIUM,58.13,0.00,False
1,missing_metadata,62.48,HIGH,79.90,36.36,False
2,suspicious,96.36,CRITICAL,100.00,90.91,True

In [9]:
# ============================================================
# TRUSTGUARD — PHASE 5B REAL-DATA BATCH VALIDATION
# ============================================================

import os
import pandas as pd
import numpy as np

BASE_DIR = r"C:\Users\Aman\Desktop\TrustGuard\product_scam_ml"

INPUT_FILE = os.path.join(
    BASE_DIR,
    "data",
    "raw",
    "phase5a_validation_results_corrected.csv.gz"
)

# ------------------------------------------------------------
# LOAD VALIDATION DATA
# ------------------------------------------------------------

df = pd.read_csv(INPUT_FILE)

print("=" * 80)
print("PHASE 5B — REAL-DATA VALIDATION")
print("=" * 80)

print(f"Rows loaded: {len(df):,}")
print(f"Columns: {len(df.columns)}")

display(df.head())

================================================================================
PHASE 5B — REAL-DATA VALIDATION
================================================================================
Rows loaded: 10,000
Columns: 32

,parent_asin,title_length,title_word_count,uppercase_ratio,special_character_ratio,description_length,description_word_count,feature_count,feature_text_length,category_count,...,log_rating_number,rating_extremeness,high_rating,low_review_count,high_rating_low_reviews,if_prediction,if_decision_score,if_score_samples,is_anomaly,anomaly_score
0,B00MCW7G9M,38,6,1.000000,0.026316,658,105,0,0,3,...,1.945910,0.5,0,1,0,1,0.028702,-0.501898,0,43.262387
1,B00YT6XQSE,29,6,0.500000,0.068966,18,4,2,35,5,...,0.693147,2.0,1,1,1,1,0.026149,-0.504451,0,44.248615
2,B07SM135LS,202,31,0.194631,0.049505,0,0,5,823,5,...,5.509388,1.5,1,0,0,1,0.106487,-0.424113,0,13.212217
3,B089CNGZCW,199,28,0.142857,0.015075,0,0,5,1102,3,...,5.455321,1.5,1,0,0,1,0.071282,-0.459318,0,26.812610
4,B004E2Z88O,38,6,0.181818,0.000000,242,34,3,142,5,...,4.174387,0.8,0,0,0,1,0.092979,-0.437621,0,18.430705

In [11]:
# ============================================================
# PHASE 5B — REAL-DATA RISK ENGINE AUDIT
# ============================================================

# Convert batch results list → DataFrame
results_df = pd.DataFrame(results)

print("=" * 80)
print("PHASE 5B — REAL-DATA RISK ENGINE AUDIT")
print("=" * 80)

print(
    f"\nProducts evaluated: {len(results_df):,}"
)


# ============================================================
# 1. CHECK AVAILABLE COLUMNS
# ============================================================

print("\nRESULT COLUMNS")
print("-" * 80)

print(
    results_df.columns.tolist()
)


# ============================================================
# 2. RISK LEVEL DISTRIBUTION
# ============================================================

print("\nRISK LEVEL DISTRIBUTION")
print("-" * 80)

risk_distribution = (
    results_df["risk_level"]
    .value_counts()
    .reindex(
        ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
        fill_value=0
    )
)

print(risk_distribution)


print("\nRISK LEVEL PERCENTAGES")
print("-" * 80)

risk_percentages = (
    risk_distribution
    / len(results_df)
    * 100
)

print(
    risk_percentages.round(2)
)


# ============================================================
# 3. ISOLATION FOREST ANOMALY DISTRIBUTION
# ============================================================

print("\nISOLATION FOREST ANOMALY DISTRIBUTION")
print("-" * 80)

print(
    results_df["is_anomaly"]
    .value_counts()
)


anomaly_percentage = (
    results_df["is_anomaly"]
    .mean()
    * 100
)

print(
    f"\nAnomaly percentage: "
    f"{anomaly_percentage:.2f}%"
)


# ============================================================
# 4. SCORE STATISTICS
# ============================================================

print("\nRISK SCORE STATISTICS")
print("-" * 80)

display(
    results_df[
        [
            "risk_score",
            "anomaly_score",
            "indicator_score"
        ]
    ].describe()
)


# ============================================================
# 5. INDICATOR PREVALENCE
# ============================================================

print("\nRISK INDICATOR PREVALENCE")
print("-" * 80)

indicator_columns = [
    "extreme_rating",
    "very_low_review_count",
    "high_rating_low_reviews",
    "missing_seller",
    "very_short_title",
    "very_short_description"
]


available_indicators = [
    col
    for col in indicator_columns
    if col in results_df.columns
]


if available_indicators:

    indicator_prevalence = (
        results_df[
            available_indicators
        ]
        .mean()
        .mul(100)
        .round(2)
        .sort_values(
            ascending=False
        )
    )

    print(
        indicator_prevalence
    )

else:

    print(
        "Indicator columns were not stored "
        "in batch results."
    )


# ============================================================
# 6. SCORE RANGE CHECK
# ============================================================

print("\nSCORE RANGE CHECK")
print("-" * 80)

print(
    "Risk score:",
    results_df["risk_score"].min(),
    "→",
    results_df["risk_score"].max()
)

print(
    "Anomaly score:",
    results_df["anomaly_score"].min(),
    "→",
    results_df["anomaly_score"].max()
)

print(
    "Indicator score:",
    results_df["indicator_score"].min(),
    "→",
    results_df["indicator_score"].max()
)


# ============================================================
# 7. RISK LEVEL CONSISTENCY
# ============================================================

invalid_levels = results_df[
    (
        (results_df["risk_score"] < 25)
        & (results_df["risk_level"] != "LOW")
    )
    |
    (
        (results_df["risk_score"] >= 25)
        & (results_df["risk_score"] < 50)
        & (results_df["risk_level"] != "MEDIUM")
    )
    |
    (
        (results_df["risk_score"] >= 50)
        & (results_df["risk_score"] < 75)
        & (results_df["risk_level"] != "HIGH")
    )
    |
    (
        (results_df["risk_score"] >= 75)
        & (results_df["risk_level"] != "CRITICAL")
    )
]


print(
    "\nInvalid risk-level assignments:",
    len(invalid_levels)
)


# ============================================================
# 8. ISOLATION FOREST PREDICTION CONSISTENCY
# ============================================================

if "if_prediction" in results_df.columns:

    invalid_predictions = results_df[
        results_df["is_anomaly"]
        != (
            results_df["if_prediction"] == -1
        )
    ]

    print(
        "Invalid anomaly predictions:",
        len(invalid_predictions)
    )

else:

    print(
        "if_prediction column not stored; "
        "skipping prediction consistency check."
    )


# ============================================================
# 9. TOP 20 HIGHEST-RISK PRODUCTS
# ============================================================

print("\nTOP 20 HIGHEST-RISK PRODUCTS")
print("-" * 80)

display_columns = [
    col
    for col in [
        "parent_asin",
        "risk_score",
        "risk_level",
        "anomaly_score",
        "indicator_score",
        "is_anomaly"
    ]
    if col in results_df.columns
]

display(
    results_df
    .sort_values(
        "risk_score",
        ascending=False
    )
    [display_columns]
    .head(20)
)


print("\n" + "=" * 80)
print("PHASE 5B REAL-DATA AUDIT COMPLETE")
print("=" * 80)

================================================================================
PHASE 5B — REAL-DATA RISK ENGINE AUDIT
================================================================================

Products evaluated: 3

RESULT COLUMNS
--------------------------------------------------------------------------------
['product', 'risk_score', 'risk_level', 'anomaly_score', 'indicator_score', 'is_anomaly']

RISK LEVEL DISTRIBUTION
--------------------------------------------------------------------------------
risk_level
LOW         0
MEDIUM      1
HIGH        1
CRITICAL    1
Name: count, dtype: int64

RISK LEVEL PERCENTAGES
--------------------------------------------------------------------------------
risk_level
LOW          0.00
MEDIUM      33.33
HIGH        33.33
CRITICAL    33.33
Name: count, dtype: float64

ISOLATION FOREST ANOMALY DISTRIBUTION
--------------------------------------------------------------------------------
is_anomaly
False    2
True     1
Name: count, dtype: int64

Anomaly percentage: 33.33%

RISK SCORE STATISTICS
--------------------------------------------------------------------------------

       risk_score  anomaly_score  indicator_score
count    3.000000       3.000000         3.000000
mean    64.573333      79.343333        42.423333
std     30.793411      20.940550        45.757295
min     34.880000      58.130000         0.000000
25%     48.680000      69.015000        18.180000
50%     62.480000      79.900000        36.360000
75%     79.420000      89.950000        63.635000
max     96.360000     100.000000        90.910000

RISK INDICATOR PREVALENCE
--------------------------------------------------------------------------------
Indicator columns were not stored in batch results.

SCORE RANGE CHECK
--------------------------------------------------------------------------------
Risk score: 34.88 → 96.36
Anomaly score: 58.13 → 100.0
Indicator score: 0.0 → 90.91

Invalid risk-level assignments: 0
if_prediction column not stored; skipping prediction consistency check.

TOP 20 HIGHEST-RISK PRODUCTS
--------------------------------------------------------------------------------

   risk_score risk_level  anomaly_score  indicator_score  is_anomaly
2       96.36   CRITICAL         100.00            90.91        True
1       62.48       HIGH          79.90            36.36       False
0       34.88     MEDIUM          58.13             0.00       False

================================================================================
PHASE 5B REAL-DATA AUDIT COMPLETE
================================================================================

In [12]:
# ============================================================
# PHASE 5B — FASTAPI PRODUCTION PARITY TEST
# ============================================================

import requests
import pandas as pd
from IPython.display import display

API_URL = "http://127.0.0.1:8000/predict"

api_results = []

for name, product in test_products.items():

    response = requests.post(
        API_URL,
        json=product,
        timeout=30
    )

    response.raise_for_status()

    result = response.json()

    api_results.append({
        "product": name,
        "risk_score": result["risk_score"],
        "risk_level": result["risk_level"],
        "anomaly_score": result["anomaly_score"],
        "indicator_score": result["indicator_score"],
        "is_anomaly": result["is_anomaly"]
    })

api_results_df = pd.DataFrame(api_results)

display(api_results_df)

,product,risk_score,risk_level,anomaly_score,indicator_score,is_anomaly
0,normal_complete,34.88,MEDIUM,58.13,0.00,False
1,missing_metadata,62.48,HIGH,79.90,36.36,False
2,suspicious,96.36,CRITICAL,100.00,90.91,True

In [13]:
# ============================================================
# PHASE 5B — INSPECT RAW AMAZON METADATA
# ============================================================

import os
import pandas as pd

BASE_DIR = r"C:\Users\Aman\Desktop\TrustGuard\product_scam_ml"

RAW_FILE = os.path.join(
    BASE_DIR,
    "data",
    "raw",
    "amazon_electronics_metadata_sample.parquet"
)

raw_df = pd.read_parquet(RAW_FILE)

print("=" * 80)
print("RAW AMAZON METADATA INSPECTION")
print("=" * 80)

print(f"Rows: {len(raw_df):,}")
print(f"Columns: {len(raw_df.columns)}")

print("\nCOLUMNS")
print("-" * 80)

for column in raw_df.columns:
    print(column)

print("\nFIRST PRODUCT")
print("-" * 80)

display(
    raw_df.iloc[0].to_frame("value")
)

================================================================================
RAW AMAZON METADATA INSPECTION
================================================================================
Rows: 10,000
Columns: 16

COLUMNS
--------------------------------------------------------------------------------
main_category
title
average_rating
rating_number
features
description
price
images
videos
store
categories
details
parent_asin
bought_together
subtitle
author

FIRST PRODUCT
--------------------------------------------------------------------------------

                                                             value
main_category                                      All Electronics
title                       FS-1051 FATSHARK TELEPORTER V3 HEADSET
average_rating                                                 3.5
rating_number                                                    6
features                                                        []
description      [Teleporter V3 The “Teleporter V3” kit sets a ...
price                                                         None
images           {'hi_res': [None], 'large': ['https://m.media-...
videos                     {'title': [], 'url': [], 'user_id': []}
store                                                    Fat Shark
categories        [Electronics, Television & Video, Video Glasses]
details          {"Date First Available": "August 2, 2014", "Ma...
parent_asin                                             B00MCW7G9M
bought_together                                                NaN
subtitle                                                       NaN
author                                                         NaN

In [15]:
# ============================================================
# PHASE 5B — REAL RAW AMAZON → FASTAPI TEST
# ============================================================

import requests
import json
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Take one REAL raw Amazon product
# ------------------------------------------------------------

raw_product = raw_df.iloc[0].to_dict()


# ------------------------------------------------------------
# Convert pandas NaN → None
#
# This is necessary because JSON cannot represent NaN
# reliably in a standard API request.
# ------------------------------------------------------------

def clean_for_json(value):

    if isinstance(value, dict):

        return {
            k: clean_for_json(v)
            for k, v in value.items()
        }

    if isinstance(value, list):

        return [
            clean_for_json(v)
            for v in value
        ]

    if isinstance(value, np.ndarray):

        return [
            clean_for_json(v)
            for v in value.tolist()
        ]

    if pd.isna(value):

        return None

    return value


raw_product = clean_for_json(
    raw_product
)


# ------------------------------------------------------------
# Send REAL Amazon product to FastAPI
# ------------------------------------------------------------

API_URL = "http://127.0.0.1:8000/predict"

response = requests.post(
    API_URL,
    json=raw_product,
    timeout=30
)

print("=" * 80)
print("REAL AMAZON PRODUCT → FASTAPI")
print("=" * 80)

print(f"HTTP Status: {response.status_code}")

response.raise_for_status()

api_result = response.json()


# ------------------------------------------------------------
# Display result
# ------------------------------------------------------------

print("\nPRODUCT")
print("-" * 80)

print(
    "Parent ASIN:",
    raw_product.get("parent_asin")
)

print(
    "Title:",
    raw_product.get("title")
)

print("\nRISK RESULT")
print("-" * 80)

print(
    json.dumps(
        api_result,
        indent=4
    )
)

================================================================================
REAL AMAZON PRODUCT → FASTAPI
================================================================================
HTTP Status: 200

PRODUCT
--------------------------------------------------------------------------------
Parent ASIN: B00MCW7G9M
Title: FS-1051 FATSHARK TELEPORTER V3 HEADSET

RISK RESULT
--------------------------------------------------------------------------------
{
    "risk_score": 37.41,
    "risk_level": "MEDIUM",
    "is_anomaly": false,
    "anomaly_score": 62.35,
    "indicator_score": 0.0,
    "isolation_forest": {
        "prediction": 1,
        "decision_score": 0.028702,
        "score_samples": -0.501898
    },
    "risk_weights": {
        "isolation_forest": 0.6,
        "risk_indicators": 0.4
    },
    "explanations": [
        {
            "type": "model",
            "indicator": "isolation_forest",
            "weight": 0.6,
            "explanation": "Product metadata shows elevated anomaly relative to the reference distribution."
        }
    ]
}

In [16]:
# ============================================================
# PHASE 5B — MULTI-PRODUCT FASTAPI PARITY VALIDATION
# ============================================================

import requests
import numpy as np
import pandas as pd
from IPython.display import display

API_URL = "http://127.0.0.1:8000/predict"

# ------------------------------------------------------------
# Number of real products to test
# ------------------------------------------------------------

N_TEST = 50

test_df = raw_df.head(N_TEST).copy()


# ------------------------------------------------------------
# Convert pandas / NumPy values into JSON-safe values
# ------------------------------------------------------------

def clean_for_json(value):

    if isinstance(value, dict):

        return {
            k: clean_for_json(v)
            for k, v in value.items()
        }

    if isinstance(value, list):

        return [
            clean_for_json(v)
            for v in value
        ]

    if isinstance(value, tuple):

        return [
            clean_for_json(v)
            for v in value
        ]

    if isinstance(value, np.ndarray):

        return [
            clean_for_json(v)
            for v in value.tolist()
        ]

    if isinstance(value, (np.integer,)):

        return int(value)

    if isinstance(value, (np.floating,)):

        if np.isnan(value):
            return None

        return float(value)

    if pd.isna(value):

        return None

    return value


# ------------------------------------------------------------
# Run DIRECT Python engine + FastAPI for every product
# ------------------------------------------------------------

parity_results = []

for index, (_, row) in enumerate(test_df.iterrows()):

    raw_product = clean_for_json(
        row.to_dict()
    )

    # --------------------------------------------------------
    # DIRECT PYTHON ENGINE
    # --------------------------------------------------------

    direct_result = predict_product_risk(
        raw_product
    )

    # --------------------------------------------------------
    # FASTAPI
    # --------------------------------------------------------

    response = requests.post(
        API_URL,
        json=raw_product,
        timeout=30
    )

    if response.status_code != 200:

        print(
            f"API ERROR at product {index}: "
            f"HTTP {response.status_code}"
        )

        print(response.text)

        raise RuntimeError(
            f"FastAPI failed at product index {index}"
        )

    api_result = response.json()

    # --------------------------------------------------------
    # COMPARE
    # --------------------------------------------------------

    risk_match = (
        direct_result["risk_score"]
        == api_result["risk_score"]
    )

    level_match = (
        direct_result["risk_level"]
        == api_result["risk_level"]
    )

    anomaly_score_match = (
        direct_result["anomaly_score"]
        == api_result["anomaly_score"]
    )

    indicator_score_match = (
        direct_result["indicator_score"]
        == api_result["indicator_score"]
    )

    anomaly_flag_match = (
        direct_result["is_anomaly"]
        == api_result["is_anomaly"]
    )

    all_match = (
        risk_match
        and level_match
        and anomaly_score_match
        and indicator_score_match
        and anomaly_flag_match
    )

    parity_results.append({

        "index":
            index,

        "parent_asin":
            raw_product.get(
                "parent_asin"
            ),

        "risk_score_direct":
            direct_result["risk_score"],

        "risk_score_api":
            api_result["risk_score"],

        "risk_level_direct":
            direct_result["risk_level"],

        "risk_level_api":
            api_result["risk_level"],

        "anomaly_score_direct":
            direct_result["anomaly_score"],

        "anomaly_score_api":
            api_result["anomaly_score"],

        "indicator_score_direct":
            direct_result["indicator_score"],

        "indicator_score_api":
            api_result["indicator_score"],

        "is_anomaly_direct":
            direct_result["is_anomaly"],

        "is_anomaly_api":
            api_result["is_anomaly"],

        "parity":
            all_match
    })


parity_df = pd.DataFrame(
    parity_results
)


# ============================================================
# FINAL PARITY REPORT
# ============================================================

print("=" * 80)
print("PHASE 5B — MULTI-PRODUCT FASTAPI PARITY VALIDATION")
print("=" * 80)

print(
    f"\nProducts tested: {len(parity_df)}"
)

print(
    f"Exact parity matches: "
    f"{parity_df['parity'].sum()}"
)

print(
    f"Parity failures: "
    f"{(~parity_df['parity']).sum()}"
)

parity_percentage = (
    parity_df["parity"].mean()
    * 100
)

print(
    f"Parity percentage: "
    f"{parity_percentage:.2f}%"
)


# ------------------------------------------------------------
# Display mismatches if any
# ------------------------------------------------------------

mismatches = parity_df[
    ~parity_df["parity"]
]

if len(mismatches) == 0:

    print("\n✓ PERFECT PARITY")
    print(
        "Direct Python engine and FastAPI "
        "returned identical results for "
        "every tested product."
    )

else:

    print("\n⚠ PARITY MISMATCHES FOUND")

    display(
        mismatches
    )


# ------------------------------------------------------------
# Show sample results
# ------------------------------------------------------------

print("\nSAMPLE RESULTS")
print("-" * 80)

display(
    parity_df[
        [
            "parent_asin",
            "risk_score_direct",
            "risk_score_api",
            "risk_level_direct",
            "risk_level_api",
            "parity"
        ]
    ].head(10)
)

print("\n" + "=" * 80)
print("MULTI-PRODUCT PARITY TEST COMPLETE")
print("=" * 80)

================================================================================
PHASE 5B — MULTI-PRODUCT FASTAPI PARITY VALIDATION
================================================================================

Products tested: 50
Exact parity matches: 50
Parity failures: 0
Parity percentage: 100.00%

✓ PERFECT PARITY
Direct Python engine and FastAPI returned identical results for every tested product.

SAMPLE RESULTS
--------------------------------------------------------------------------------

,parent_asin,risk_score_direct,risk_score_api,risk_level_direct,risk_level_api,parity
0,B00MCW7G9M,37.41,37.41,MEDIUM,MEDIUM,True
1,B00YT6XQSE,67.45,67.45,HIGH,HIGH,True
2,B07SM135LS,12.12,12.12,LOW,LOW,True
3,B089CNGZCW,25.21,25.21,MEDIUM,MEDIUM,True
4,B004E2Z88O,13.50,13.50,LOW,LOW,True
5,B00TX536EK,6.38,6.38,LOW,LOW,True
6,B07BJ7ZZL7,13.91,13.91,LOW,LOW,True
7,B005G99O2U,16.12,16.12,LOW,LOW,True
8,B01MCZP7RF,50.27,50.27,HIGH,HIGH,True
9,B00R6R82HS,11.59,11.59,LOW,LOW,True

================================================================================
MULTI-PRODUCT PARITY TEST COMPLETE
================================================================================

In [17]:
# ============================================================
# PHASE 5B — SAVE FASTAPI PARITY REPORT
# ============================================================

import os
import json
from datetime import datetime

BASE_DIR = r"C:\Users\Aman\Desktop\TrustGuard\product_scam_ml"

REPORT_FILE = os.path.join(
    BASE_DIR,
    "reports",
    "phase5b_fastapi_parity_report.json"
)

report = {
    "phase": "5B",
    "validation": "FastAPI Production Risk Engine Parity",
    "timestamp": datetime.now().isoformat(),

    "products_tested": int(
        len(parity_df)
    ),

    "exact_parity_matches": int(
        parity_df["parity"].sum()
    ),

    "parity_failures": int(
        (~parity_df["parity"]).sum()
    ),

    "parity_percentage": float(
        parity_df["parity"].mean() * 100
    ),

    "status":
        "PASS"
        if parity_df["parity"].all()
        else "FAIL",

    "validation_checks": {
        "risk_score": True,
        "risk_level": True,
        "anomaly_score": True,
        "indicator_score": True,
        "is_anomaly": True
    },

    "model": (
        "trustguard_metadata_isolation_forest.joblib"
    ),

    "calibration": (
        "trustguard_risk_calibration.json"
    ),

    "conclusion": (
        "Direct Python risk engine and FastAPI "
        "production endpoint returned identical "
        "results for all tested real Amazon products."
    )
}

with open(
    REPORT_FILE,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        report,
        f,
        indent=4
    )

print("=" * 80)
print("PHASE 5B PARITY REPORT SAVED")
print("=" * 80)

print(
    f"\n✓ File: {REPORT_FILE}"
)

print(
    f"✓ Products tested: "
    f"{report['products_tested']}"
)

print(
    f"✓ Parity: "
    f"{report['parity_percentage']:.2f}%"
)

print(
    f"✓ Status: "
    f"{report['status']}"
)

================================================================================
PHASE 5B PARITY REPORT SAVED
================================================================================

✓ File: C:\Users\Aman\Desktop\TrustGuard\product_scam_ml\reports\phase5b_fastapi_parity_report.json
✓ Products tested: 50
✓ Parity: 100.00%
✓ Status: PASS

In [18]:
# ============================================================
# PHASE 5B — FASTAPI CONTRACT & EDGE-CASE AUDIT
# ============================================================

import requests
import json
import pandas as pd
from IPython.display import display


API_BASE = "http://127.0.0.1:8000"


# ============================================================
# TEST 1 — HEALTH ENDPOINT
# ============================================================

print("=" * 80)
print("TEST 1 — HEALTH ENDPOINT")
print("=" * 80)

response = requests.get(
    f"{API_BASE}/health",
    timeout=10
)

print("HTTP Status:", response.status_code)
print("Response:", response.json())

assert response.status_code == 200
assert response.json()["status"] == "healthy"

print("✓ HEALTH CHECK PASSED")


# ============================================================
# TEST 2 — ROOT ENDPOINT
# ============================================================

print("\n" + "=" * 80)
print("TEST 2 — ROOT ENDPOINT")
print("=" * 80)

response = requests.get(
    f"{API_BASE}/",
    timeout=10
)

print("HTTP Status:", response.status_code)
print("Response:", response.json())

assert response.status_code == 200

print("✓ ROOT ENDPOINT PASSED")


# ============================================================
# TEST 3 — VALID PRODUCT
# ============================================================

print("\n" + "=" * 80)
print("TEST 3 — VALID PRODUCT")
print("=" * 80)

valid_product = {
    "parent_asin": "TEST001",

    "title":
        "Wireless Bluetooth Headphones",

    "description":
        "High quality wireless headphones "
        "with long battery life.",

    "features": [
        "Bluetooth",
        "Noise cancellation",
        "Long battery life"
    ],

    "categories": [
        "Electronics",
        "Headphones"
    ],

    "images": {
        "large": [
            "https://example.com/image.jpg"
        ]
    },

    "videos": {
        "url": []
    },

    "seller":
        "Test Electronics",

    "price":
        "49.99",

    "average_rating":
        4.2,

    "rating_number":
        150
}

response = requests.post(
    f"{API_BASE}/predict",
    json=valid_product,
    timeout=30
)

print("HTTP Status:", response.status_code)

assert response.status_code == 200

valid_result = response.json()

print(
    json.dumps(
        valid_result,
        indent=4
    )
)

assert 0 <= valid_result["risk_score"] <= 100
assert 0 <= valid_result["anomaly_score"] <= 100
assert 0 <= valid_result["indicator_score"] <= 100

assert valid_result["risk_level"] in [
    "LOW",
    "MEDIUM",
    "HIGH",
    "CRITICAL"
]

print("✓ VALID PRODUCT TEST PASSED")


# ============================================================
# TEST 4 — MINIMAL / MISSING METADATA
# ============================================================

print("\n" + "=" * 80)
print("TEST 4 — MISSING METADATA")
print("=" * 80)

minimal_product = {}

response = requests.post(
    f"{API_BASE}/predict",
    json=minimal_product,
    timeout=30
)

print("HTTP Status:", response.status_code)

assert response.status_code == 200

minimal_result = response.json()

print(
    json.dumps(
        minimal_result,
        indent=4
    )
)

assert 0 <= minimal_result["risk_score"] <= 100

print("✓ MISSING METADATA TEST PASSED")


# ============================================================
# TEST 5 — SUSPICIOUS PRODUCT
# ============================================================

print("\n" + "=" * 80)
print("TEST 5 — SUSPICIOUS PRODUCT")
print("=" * 80)

suspicious_product = {

    "title":
        "Amazing Product",

    "description":
        "Best product ever.",

    "features": [],

    "categories": [
        "Electronics"
    ],

    "images": {},

    "videos": {},

    "seller":
        "",

    "price":
        "9.99",

    "average_rating":
        5.0,

    "rating_number":
        2
}

response = requests.post(
    f"{API_BASE}/predict",
    json=suspicious_product,
    timeout=30
)

print("HTTP Status:", response.status_code)

assert response.status_code == 200

suspicious_result = response.json()

print(
    json.dumps(
        suspicious_result,
        indent=4
    )
)

assert suspicious_result["risk_level"] in [
    "HIGH",
    "CRITICAL"
]

print("✓ SUSPICIOUS PRODUCT TEST PASSED")


# ============================================================
# TEST 6 — INVALID FIELD TYPE
# ============================================================

print("\n" + "=" * 80)
print("TEST 6 — INVALID FIELD TYPE")
print("=" * 80)

invalid_product = {

    "title":
        "Test Product",

    "average_rating":
        "NOT_A_NUMBER",

    "rating_number":
        10
}

response = requests.post(
    f"{API_BASE}/predict",
    json=invalid_product,
    timeout=30
)

print("HTTP Status:", response.status_code)

print(
    response.text
)

assert response.status_code == 422

print("✓ INVALID INPUT TEST PASSED")


# ============================================================
# TEST 7 — RESPONSE SCHEMA
# ============================================================

print("\n" + "=" * 80)
print("TEST 7 — RESPONSE SCHEMA")
print("=" * 80)

required_fields = [
    "risk_score",
    "risk_level",
    "is_anomaly",
    "anomaly_score",
    "indicator_score",
    "isolation_forest",
    "risk_weights",
    "explanations"
]

missing_fields = [
    field
    for field in required_fields
    if field not in valid_result
]

print(
    "Missing fields:",
    missing_fields
)

assert len(missing_fields) == 0

print("✓ RESPONSE SCHEMA PASSED")


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("PHASE 5B — API CONTRACT & EDGE-CASE AUDIT COMPLETE")
print("=" * 80)

print("""
✓ Health endpoint
✓ Root endpoint
✓ Valid product
✓ Missing metadata
✓ Suspicious product
✓ Invalid input handling
✓ Response schema

PHASE 5B API CONTRACT STATUS: PASS
""")

================================================================================
TEST 1 — HEALTH ENDPOINT
================================================================================
HTTP Status: 200
Response: {'status': 'healthy', 'service': 'trustguard-risk-engine', 'version': '5.0.0'}
✓ HEALTH CHECK PASSED

================================================================================
TEST 2 — ROOT ENDPOINT
================================================================================
HTTP Status: 200
Response: {'service': 'TrustGuard Product Risk API', 'version': '5.0.0', 'status': 'running', 'endpoints': {'health': 'GET /health', 'prediction': 'POST /predict'}}
✓ ROOT ENDPOINT PASSED

================================================================================
TEST 3 — VALID PRODUCT
================================================================================
HTTP Status: 200
{
    "risk_score": 54.97,
    "risk_level": "HIGH",
    "is_anomaly": false,
    "anomaly_score": 79.5,
    "indicator_score": 18.18,
    "isolation_forest": {
        "prediction": 1,
        "decision_score": 0.001033,
        "score_samples": -0.529567
    },
    "risk_weights": {
        "isolation_forest": 0.6,
        "risk_indicators": 0.4
    },
    "explanations": [
        {
            "type": "risk_indicator",
            "indicator": "missing_seller",
            "weight": 1.0,
            "explanation": "Seller information is missing."
        },
        {
            "type": "model",
            "indicator": "isolation_forest",
            "weight": 0.6,
            "explanation": "Product metadata is highly anomalous relative to the reference metadata distribution."
        }
    ]
}
✓ VALID PRODUCT TEST PASSED

================================================================================
TEST 4 — MISSING METADATA
================================================================================
HTTP Status: 200
{
    "risk_score": 64.56,
    "risk_level": "HIGH",
    "is_anomaly": true,
    "anomaly_score": 83.37,
    "indicator_score": 36.36,
    "isolation_forest": {
        "prediction": -1,
        "decision_score": -0.005207,
        "score_samples": -0.535807
    },
    "risk_weights": {
        "isolation_forest": 0.6,
        "risk_indicators": 0.4
    },
    "explanations": [
        {
            "type": "risk_indicator",
            "indicator": "missing_seller",
            "weight": 1.0,
            "explanation": "Seller information is missing."
        },
        {
            "type": "model",
            "indicator": "isolation_forest",
            "weight": 0.6,
            "explanation": "Product metadata is highly anomalous relative to the reference metadata distribution."
        },
        {
            "type": "risk_indicator",
            "indicator": "very_short_title",
            "weight": 0.5,
            "explanation": "Product title is unusually short."
        },
        {
            "type": "risk_indicator",
            "indicator": "very_short_description",
            "weight": 0.5,
            "explanation": "Product description is unusually short."
        }
    ]
}
✓ MISSING METADATA TEST PASSED

================================================================================
TEST 5 — SUSPICIOUS PRODUCT
================================================================================
HTTP Status: 200
{
    "risk_score": 96.36,
    "risk_level": "CRITICAL",
    "is_anomaly": true,
    "anomaly_score": 100.0,
    "indicator_score": 90.91,
    "isolation_forest": {
        "prediction": -1,
        "decision_score": -0.057495,
        "score_samples": -0.588095
    },
    "risk_weights": {
        "isolation_forest": 0.6,
        "risk_indicators": 0.4
    },
    "explanations": [
        {
            "type": "risk_indicator",
            "indicator": "high_rating_low_reviews",
            "weight": 1.5,
            "explanation": "Product has a high rating but very few reviews."
        },
        {
            "type": "risk_indicator",
            "indicator": "extreme_rating",
            "weight": 1.0,
            "explanation": "Product has an unusually extreme rating."
        },
        {
            "type": "risk_indicator",
            "indicator": "very_low_review_count",
            "weight": 1.0,
            "explanation": "Product has very few reviews."
        },
        {
            "type": "risk_indicator",
            "indicator": "missing_seller",
            "weight": 1.0,
            "explanation": "Seller information is missing."
        },
        {
            "type": "model",
            "indicator": "isolation_forest",
            "weight": 0.6,
            "explanation": "Product metadata is highly anomalous relative to the reference metadata distribution."
        }
    ]
}
✓ SUSPICIOUS PRODUCT TEST PASSED

================================================================================
TEST 6 — INVALID FIELD TYPE
================================================================================
HTTP Status: 422
{"detail":[{"type":"float_parsing","loc":["body","average_rating"],"msg":"Input should be a valid number, unable to parse string as a number","input":"NOT_A_NUMBER"}]}
✓ INVALID INPUT TEST PASSED

================================================================================
TEST 7 — RESPONSE SCHEMA
================================================================================
Missing fields: []
✓ RESPONSE SCHEMA PASSED

================================================================================
PHASE 5B — API CONTRACT & EDGE-CASE AUDIT COMPLETE
================================================================================

✓ Health endpoint
✓ Root endpoint
✓ Valid product
✓ Missing metadata
✓ Suspicious product
✓ Invalid input handling
✓ Response schema

PHASE 5B API CONTRACT STATUS: PASS

In [19]:
# ============================================================
# PHASE 5B — SAVE API CONTRACT AUDIT REPORT
# ============================================================

import os
import json
from datetime import datetime

BASE_DIR = r"C:\Users\Aman\Desktop\TrustGuard\product_scam_ml"

REPORT_FILE = os.path.join(
    BASE_DIR,
    "reports",
    "phase5b_api_contract_audit.json"
)

report = {
    "phase": "5B",
    "validation": "FastAPI API Contract and Edge-Case Audit",
    "timestamp": datetime.now().isoformat(),

    "tests": {
        "health_endpoint": {
            "status_code": 200,
            "status": "PASS"
        },

        "root_endpoint": {
            "status_code": 200,
            "status": "PASS"
        },

        "valid_product": {
            "status_code": 200,
            "status": "PASS"
        },

        "missing_metadata": {
            "status_code": 200,
            "status": "PASS"
        },

        "suspicious_product": {
            "status_code": 200,
            "status": "PASS"
        },

        "invalid_field_type": {
            "status_code": 422,
            "status": "PASS"
        },

        "response_schema": {
            "missing_fields": [],
            "status": "PASS"
        }
    },

    "overall_status": "PASS",

    "conclusion": (
        "FastAPI health, root, prediction, validation-error, "
        "edge-case, and response-schema tests all passed."
    )
}

with open(
    REPORT_FILE,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        report,
        f,
        indent=4
    )

print("=" * 80)
print("PHASE 5B API CONTRACT AUDIT REPORT SAVED")
print("=" * 80)

print(f"\n✓ File: {REPORT_FILE}")
print("✓ Overall status: PASS")

================================================================================
PHASE 5B API CONTRACT AUDIT REPORT SAVED
================================================================================

✓ File: C:\Users\Aman\Desktop\TrustGuard\product_scam_ml\reports\phase5b_api_contract_audit.json
✓ Overall status: PASS

In [20]:
import requests
import json

url = "http://localhost:5000/api/products"

product = {
    "parent_asin": "B00MCW7G9M",
    "title": "FS-1051 FATSHARK TELEPORTER V3 HEADSET",
    "description": "The Teleporter V3 kit provides a high quality video experience.",
    "features": [],
    "categories": [
        "Electronics",
        "Television & Video",
        "Video Glasses"
    ],
    "images": {
        "large": [
            "https://m.media-amazon.com/images/example.jpg"
        ]
    },
    "videos": {
        "url": []
    },
    "store": "Fat Shark",
    "price": None,
    "average_rating": 3.5,
    "rating_number": 6
}

response = requests.post(
    url,
    json=product
)

print("HTTP Status:", response.status_code)
print(json.dumps(response.json(), indent=4))

HTTP Status: 200
{
    "risk_score": 33.28,
    "risk_level": "MEDIUM",
    "is_anomaly": false,
    "anomaly_score": 55.46,
    "indicator_score": 0,
    "isolation_forest": {
        "prediction": 1,
        "decision_score": 0.039811,
        "score_samples": -0.490789
    },
    "risk_weights": {
        "isolation_forest": 0.6,
        "risk_indicators": 0.4
    },
    "explanations": [
        {
            "type": "model",
            "indicator": "isolation_forest",
            "weight": 0.6,
            "explanation": "Product metadata shows elevated anomaly relative to the reference distribution."
        }
    ]
}